public class UtilityData {
    //public Static String label0To90           = 'Last_N_Days:90';
    //public Static String label0To180          = 'Last_N_Days:180';
    public Static String label0To12             = 'LAST_N_Days:365';
    //public Static String label0To24           = 'LAST_N_Days:730';
    //public Static String labelAll             = 'All';
    public Static String labelLastRefreshDate   = 'Last_Refresh_Datetime';
    public Static String labelErrorDMLRows      = 'DMLRows';
    public Static String labelP360ReleaseDate   = 'P360 Release date';
    public Static String labelErrorHeapSize     = 'HeapSize';
    //public Static String labelforAllDate      = '01-01-2010';
    //public Static String labelforAllDateApex  = '01/01/2010';
    public Static Integer labelgetNxtMonth      = -1;
    public Static String labelforBasicProfle    = 'Basic Access';
    public Static String labelforClinicalProfile = 'Clinical Access';
    public Static String usernameSuffix = '.P360.QASB1';
    public Static String labelforDate            = '01-01-2014'; //dd-mm-yyyy
    //public static String labelforRscTypeObs    = '"resourceType": "Observation"';
    public static String labelforRscTypeEnc      = '"resourceType": "Condition"';
    public static String obsResourceName         = 'Observation';
    public static String labelforRscTypeProbList = '"id":'; 
 
}